= README
:author: Thomas S. Phillips
:toc:
:toclevels: 2
:numbered:

Too many projects; brain scrambled.
Reboot.
This package is being redesigned.

== Perry Sim Manifesto

=== A virtual world simulator focusing on semantics.

Simulate the relationships amongst entities, agents, and the world.
The world consists of rules, dynamic entities, and agents that are entities with agency.
Agents may be autonomous or controlled by real people.

=== The world is infinite.

The scope of the simulation is infinite and can run standalone in a web browser.
Although the code is separated between client and server, both can run in a single web browser.
A world of infinite scope can be generated from a single seed.
A seed consists of four 32-bit signed integers ([0,0,0,0] excluded), which means there are 2^128 - 1 possible infinite worlds.

A world is a combination of an initial seed and a generator.
A generator is a set of functions that procedurally generate content based on an initial seed.
Changes to the world are limited to the storage capacity of the server.
Changes can include insertions, deletions, and modifications.

=== Client and server are separable.

The server hosts a model of the world, while a client is merely a view into that model.
Different clients can then provide different views into the same model.
Some clients may be simple and straightforward, while others may be elaborate physics simulations.

=== No external dependencies.

Why?
Because other libraries are perpetually moving targets.
I do not want to constantly chase changes in other libraries.
I think the eternal evolution of dependencies is a bad habit the Internet needs to kick.

== Definitions

Entity::
    A thing in the world with its own state.
    Each entity references the Sim.

Sim::
    The simulation, referenced by the Perry.Sim variable.
Entity::
    A thing in the world with its own state.
    Each entity references the Sim.
Zone::
    A collection of semantically-related scenes.
Scene::
    A semantic locale that contains agents.
    Also contains a 2-dimensional space.
Agent::
    An entity that interacts with the world on its own volition.


== Q&A

[qanda]
Why the name "Perry Sim?"::
    In 1985, Infocom released a text adventure game titled _A Mind Forever Voyaging_, which was written by Steve Meretzky.
    In the game there was a sentient computer called PRISM that was used to simulate society.
    PRISM had a persona named Perry Sim.
    Thus, the project name is an homage to Steve Meretzy and _A Mind Forever Voyaging_.

What is the project logo?::
    The project logo is a platypus named Perry, paying homage to Perry the Platypus (AKA "Agent P"), who was a semi-aquatic egg-laying mammal of action.
    Perry was a major character in the Phineas and Ferb cartoon series.

Why is the project in Javascript?::
    Perry Sim is meant to be a self-contained platform that can run as easily as possible on as many platforms as possible.
    Because of the ubiquity of web browsers and Javascript, the language choice seemed to make sense.

What is Perry Sim best suited for?::
    Perry Sim is best suited for interactive fiction and role-playing games.
    In particular, applications that benefit from an isometric view of the world.
    The project is _not_ meant to be a general purpose game framework.

Does the platform support multi-player games?::
    Yes, that is a long-term goal. For now, the main focus is on self-contained packages, to include games, simulations, educational applications, and interactive fiction.

Who made Perry Sim?::
    Thomas S. Phillips is the author and maintainer of Perry Sim. He likes exhaustingly long walks, cats and other predators, guns and ammo, explosives and other dangerous things, mathematics, linguistics, music, and tacos.
